### ISSUE TITLE
Application token

### ISSUE THREAD

**Issue by rares-preda** [youtube/yt-direct-lite-iOS#6]
I'm trying to create an application that capture video from the front camera and after, I want to upload that video on the company channel. The problem is that the app will be used by many people and on oAuth2.0 I know that the user should write his email and password. I want to skip this step, and for everyone who use the app, the videos should upload on the owner channel. I know that facebook and twitter give you an application token that never expire and you can use it. Is this possible to do that on youtube api ?

**Comment by ulukaya** [comment]
Nope, and Direct Lite is the only workaround.
