### ISSUE TITLE
I am able to compile and run the sample app but unable to function properly.

### ISSUE THREAD

**Issue by shyamalschandra** [youtube/yt-direct-lite-iOS#8]
![image](https://cloud.githubusercontent.com/assets/9545735/5938007/371d7e7a-a6bc-11e4-97ca-e0ca80b2ce18.png)

![image](https://cloud.githubusercontent.com/assets/9545735/5938008/3ee7cd04-a6bc-11e4-85d5-e93e5138dc1f.png)

I would like to have it at least functioning before using it as a template for future projects.

**Comment by ulukaya** [comment]
I wish you at least had read the README and followed the steps before writing this!
